/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    ValueBlock: typeof import('./src/components/ValueBlock.vue')['default']
    ValueTable: typeof import('./src/components/ValueTable.vue')['default']
  }
}
